DROP DATABASE IF EXISTS collegeCraft;
CREATE DATABASE IF NOT EXISTS collegeCraft;
USE collegeCraft;
DROP TABLE IF EXISTS users, roles, product, comments, sells, reputation;
CREATE TABLE users (username varchar(15) NOT NULL UNIQUE, hashed_password varchar(255) NOT NULL, email_address varchar(30), user_id INT AUTO_INCREMENT, bio varchar(512), reputation_id INT, role_id INT, location varchar(128), name varchar(32), PRIMARY KEY (user_id));
CREATE TABLE roles (role_id INT, role varchar(20), PRIMARY KEY (role_id)); 
CREATE TABLE product (product_id INT, description varchar(256), price INT NOT NULL, category varchar(256), PRIMARY KEY (product_id));
CREATE TABLE reputation (reputation_id INT, trust_level INT, statistics varchar(256), PRIMARY KEY (reputation_id)); 
CREATE TABLE sells (user_id INT, product_id INT, PRIMARY KEY (user_id, product_id), FOREIGN KEY (user_id) REFERENCES users(user_id), FOREIGN KEY (product_id) REFERENCES product(product_id));
CREATE TABLE comments (comment_id INT, product_id INT, reviewer INT NOT NULL, review varchar(256), rating INT, PRIMARY KEY (comment_id), FOREIGN KEY (product_id) REFERENCES product(product_id), FOREIGN KEY (reviewer) REFERENCES users(user_id));
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User0','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User0@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User1','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User1@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User2','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User2@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User3','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User3@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User4','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User4@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User5','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User5@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User6','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User6@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User7','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User7@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User8','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User8@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User9','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User9@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User10','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User10@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User11','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User11@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User12','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User12@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User13','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User13@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User14','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User14@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User15','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User15@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User16','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User16@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User17','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User17@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User18','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User18@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User19','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User19@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User20','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User20@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User21','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User21@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User22','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User22@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User23','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User23@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User24','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User24@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User25','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User25@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User26','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User26@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User27','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User27@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User28','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User28@gmail.com');
INSERT INTO users (username, hashed_password,bio,email_address) VALUES ('User29','$1$salt0123$NzklwD3/qBRY6m8l6jGfg1','Excited to join the community, meet new users, and see whats up!','User29@gmail.com');
